### ISSUE TITLE
HU-001-TA003 Crear footer

### ISSUE THREAD

**Issue by Poipurin** [Poipurin/Ladera#12]
Crear footer estructura básica HTML
[Referencia](https://www.figma.com/file/ZZBcJHStxDP9d4B0c09Inn/Ladera?node-id=0%3A1&t=tqm6qSGEiDThyHEJ-1)

**Comment by ArielRetamales1593** [comment]
Holaa, cómo estai? 

No encuentro el logo, me lo puedes enviar por acá por fa :o

**Comment by Poipurin** [comment]
![logo_blanco](https://user-images.githubusercontent.com/108783960/227813363-6d9eca63-2e09-4cc3-a8fd-1e2b359f4908.png)
Ahí va! no sé si sirva en este formato peor se intenta jaj

**Comment by ArielRetamales1593** [comment]
Me faltó centrar los textos , recién caché. En un ratito lo arreglo. 

Avísame cualquier cosa 👍

**Comment by Poipurin** [comment]
tranqui! era solo el html por ahora!
